### ISSUE TITLE
Deployment 2021-1.0 checklist

### ISSUE THREAD

**Issue by mrakitin** [NSLS-II-SMI/profile_collection#18]
## Current collection workstations

```
xf12id-ws1  # main "workhorse" collection workstation
```

## Previsit 

- [x] Enable Azure-Pipelines CI
- [x] Make sure that the current latest environments are pushed to all the bl machines
- [x] Skim the IPython startup files in `profile_collection`
  - Check if it's safe to start `bsui` remotely (does it touch any hardware?) - use `git grep .put` or `git grep caput`
- [x] Check for outstanding PRs and issues on beamline repos
- [x] Branch https://github.com/NSLS-II/playbooks for the purpose of updating the SMI `current_env_tag` in the `production` file (https://github.com/NSLS-II/playbooks/pull/427).

## Housekeeping 

- [x] Update `/opt/conda/.condarc` and `conda` with ansible
  ```bash
  $ ansible-playbook -i production install-base-conda.yml --limit=SMI -kK -vvvv
  ```
- [x] Add BL staff to the BL GitHub organization as owners
- [x] Work with BL staff to commit any un-committed changes to their profiles
- [x] Tag the `profile_collection` repository as-found as `2020C2.1` and push to GitHub
   ```bash
   $ git tag 2020C2.1 -m "Before 2021C1.0 deployment"
   ```
- [x] Discuss with BL staff which conda envs they want to keep/delete and perform the cleanup
- [x] Check/update the beamline's workstation inventory with the BL staff (in https://github.com/NSLS-II/playbooks/blob/master/production)
- [x] Ask beamline staff about the beamline unix group they want to use for bluesky logs. The members of the group can be checked with the following command:
  ```bash
  $ getent group smi
  ```
  Add this group name to the collection vars in the inventory file (see [this example](https://github.com/NSLS-II/playbooks/pull/424/files#diff-ab8e18ef4ebebeddc0b3152ce9c9006e14fc05242e3fc9ce32246ea6a9543074R666-R668)).
- [x] In `~/.bashrc`, if necessary, update the logging environment variables to use directory `/var/log/bluesky/...` and add `umask 0002`.
  ```bash
  umask u=rwx,g=rwx,o=rx  # 0002
  export BLUESKY_LOG_FILE=/var/log/bluesky/bluesky.log
  export BLUESKY_IPYTHON_LOG_FILE=/var/log/bluesky/bluesky_ipython.log
  ```
  and (if needed) create that directory with the following permissions and ownership:
  ```bash
  # sudo mkdir /var/log/bluesky
  # sudo chown -Rv xf12id:smi /var/log/bluesky
  # sudo chmod -Rv g+rws /var/log/bluesky
  ```
  Remember to `source ~/.bashrc`.
- [x] Remove explicit setting of ophyd logging level from the first startup script
- [x] Double-check that if there is an open PR removing handlers, it is merged (and tested).
- [x] Update vendored copy of `PersistentDict` to bug-fixed version (see the updated gist snippet: https://gist.github.com/jklynch/a4366b8900ec0c03883403455ae711b2).
- [x] Make sure all repos have the BSD-3-Clause licenses (see https://github.com/NSLS-II-SRX/profile_collection/pull/16 as an example)

## Test deployment 

- [x] Run profile against new environment
  ```bash
  $ BS_ENV=collection-2021-1.0 bsui
  ```
  It may be necessary to disable `jedi` in `ipython`. Add this to the `ipython` command line arguments in`bsui`:
  ```bash
  --IPCompleter.use_jedi=False
  ```
- [x] Update the profile as needed to run
- [x] Test databroker v2
  ```py
  from databroker import catalog
  cat = catalog['smi']
  cat[-1].primary.read()
  ```
- [x] Run acceptance tests (if any) and run a representative set of scans for the beamline

## Finish

- [x] Tag the updated profile as `2021C1.0`
   ```bash
   $ git tag 2021C1.0 -m "After 2021C1.0 deployment"
   ```
- [x] Open and merge a PR against https://github.com/NSLS-II/playbooks setting `current_env_tag="2021-1.0"` for the SMI beamline
- [x] Update `bsui` via ansible to use the new environment (http://nsls-ii.github.io/deployment/upgrading-beamlines.html#change-bsui-s-default-environment)

**Comment by mrakitin** [comment]
Successfully finished the deployment! Thanks everyone :)
